# Generated by Django 4.2 on 2024-03-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scraper.keyword'),
        ),
    ]
