# Generated by Django 4.2 on 2024-04-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_adminactionholder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminActionHolder',
        ),
    ]
